dbfilename redis_cache.rdb
dir /home/manonraj/HR/config/pids
pidfile /home/manonraj/HR/config/pids/redis_cache.pid
bind 127.0.0.1
port 13015
maxmemory 384mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/manonraj/HR/config/redis_cache.acl
